### ISSUE TITLE
Unable to build Android seed project

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-xamarin-oidc-samples#1]
*Device Information*
IDE: Xamarin Studio
Platform: Android
URL:https://auth0.com/docs/quickstart/native/xamarin

*Description
When the user tries to run the project, there's no readme file specifying for anything to be done before building. So when the user just opens the solution in Xamarin Studio and clicks on Run, 2 build errors show up.

*Screenshot*
<img width="1156" alt="screen shot 2017-06-01 at 8 11 45 pm" src="https://cloud.githubusercontent.com/assets/5594487/26705961/a6b213c0-4707-11e7-8a96-f85251f418f7.png">

**Comment by jerriep** [comment]
Did you restore the NuGet packages?

**Comment by jerriep** [comment]
You require Visual Studio for Mac. And you will need to to restore NuGet package before building the project.
