### ISSUE TITLE
Login not authorized error in app after auth0 login

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-xamarin-oidc-samples#16]
In the [Xamarin QS](https://auth0.com/docs/quickstart/native/xamarin/01-login) sample, after building and running the application the user is not able to log in. After the user inputs the credentials in the Auth0 Login, it redirects back to the app which is expected, but an error shows up saying the user is not authorized. This happens on both Android and iOS.

**Screenshots**
![image](https://user-images.githubusercontent.com/5594487/46983705-c6534400-d0af-11e8-88cb-29581dd1ef4a.png)
![android error](https://user-images.githubusercontent.com/5594487/46983709-c9e6cb00-d0af-11e8-9785-bb0322cbbc62.png)

**Logs**
[logcat-android.txt](https://github.com/auth0-community/auth0-xamarin-oidc-samples/files/2480867/logcat-android.txt)
[logcat-ios.txt](https://github.com/auth0-community/auth0-xamarin-oidc-samples/files/2480868/logcat-ios.txt)

**Comment by mikearias3** [comment]
After digging a bit deeper looks like this error is caused because the Authorization Prompt is not showing up.

![auth logs](https://user-images.githubusercontent.com/5594487/47097032-79ca4e80-d1fe-11e8-8ee3-4fc6d9ee6740.PNG)
![authorization error](https://user-images.githubusercontent.com/5594487/47097033-7a62e500-d1fe-11e8-868f-ce53a4d8db74.png)

**Comment by damieng** [comment]
Not able to reproduce this here.
