### ISSUE TITLE
Warnings present in Xamarin Android Seed Project

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-xamarin-oidc-samples#2]
*Device Information*
IDE: Xamarin Studio
Platform: Android
URL:https://auth0.com/docs/quickstart/native/xamarin

*Description
When the user tries to run the project, there's no readme file specifying for anything to be done before building. So when the user just opens the solution in Xamarin Studio and clicks on Run, 2 warning messages show up.

*Screenshot*
<img width="1153" alt="screen shot 2017-06-01 at 8 15 37 pm" src="https://cloud.githubusercontent.com/assets/5594487/26706025/2645e530-4708-11e7-892c-f5c0b5fd8a8a.png">

**Comment by jerriep** [comment]
Please ensure that you use Visual Studio Mac, and not Xamarin Studio
