### ISSUE TITLE
Unable to open iOS Xamarin seed project

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-xamarin-oidc-samples#3]
*Device Information*
IDE: Xamarin Studio
Platform: iOS
URL:https://auth0.com/docs/quickstart/native/xamarin

*Description
When the user tries to run the project, there's no readme file specifying for anything to be done before building. So when the user just opens the solution in Xamarin Studio, an error message shows up immediately.

*Screenshot*
<img width="719" alt="screen shot 2017-06-01 at 8 25 44 pm" src="https://cloud.githubusercontent.com/assets/5594487/26706114/d8082c2e-4708-11e7-8d53-157fda77a439.png">

**Comment by jerriep** [comment]
You require Visual Studio for Mac. And you will need to to restore NuGet package before building the project.
