### ISSUE TITLE
Possible to skip auth0's portal login page to connection logins?

### ISSUE THREAD

**Issue by j-nguyen** [auth0-samples/auth0-xamarin-oidc-samples#31]
Hi, I was wondering if it was possible to skip the login portal page directly to one of the connections? Like for example to skip directly into Google's login page?

**Comment by konradsopala** [comment]
Hey there!

Don't have Xamarin experience but in general it's doable. You need to pass the connection parameter in the /authorize URL. 

```
https://[tenant].auth0.com/authorize?
audience=[API Identifier]
&scope=openid+profile+email
&response_type=token
&client_id=[Client ID]&connection=[Connection name]
&redirect_uri=[Redirect URI]
&nonce=123
```
