### ISSUE TITLE
How to Sign in and sign up user

### ISSUE THREAD

**Issue by PrachiKarapurkar** [auth0-samples/auth0-xamarin-oidc-samples#34]
How to sign in and sign up user with oidc on xamarin android and iOS?

**Comment by frederikprijck** [comment]
Sorry for not getting back to this. I assume this is no longer an open question. 

However, for anyone reaching this issue, you can login by calling the Auth0Client's `LoginAsync` method.

For SignUp, you should pass `new { screen_hint ="signup" }` as `extraParameters` to that very same `LoginAsync` method.
