### ISSUE TITLE
no readme's

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-xamarin-oidc-samples#4]
(AUTH-4111)
Samples contains no readme's

**Comment by dagostinelli** [comment]
+1 

Some instructions would be nice.  There are some tasks that you are supposed to just know to do:

- set the client_id
- set the domain 
- correctly setting up the callback url in the management console (it has a very specific format)

**Comment by jerriep** [comment]
@dagostinelli This sample code is supplementary to the Xamarin Quickstart. Please refer to that for a step-by-step guide on how to implement:
https://auth0.com/docs/quickstart/native/xamarin
