### ISSUE TITLE
Login browser appears again after successfully login on Xamarin Forms (Android)

### ISSUE THREAD

**Issue by juniorsaraviao** [auth0-samples/auth0-xamarin-oidc-samples#47]
# Issue Report

### Description

When the login is successful and then the app is closed using **Phone back button**, the login browser appears again (Auth0.OidcClient.AndroidX v3.2.4).

### Expected behaviour

Close the login browser so that when pressing the Phone back button, the browser doesn't appear again.

### Actual behaviour 

The login browser appears again after pressing the Phone back button.

### Steps to reproduce the problem

1. Use the Auth0 Xamarin sample [here](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/tree/master/Samples/Forms_NS/FormsSample) or create a project following these [steps](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/tree/master/Samples/Forms_NS#getting-started).
2. Log in with valid credentials.
3. Press the phone back button on the bottom.
4. The login browser appears again.

### Language / Framework Versions

1. **Language used:** C#
2. **Framework used:** Xamarin forms (v5.0.0.2337)

### Testing environment

1. **Operating system:** Windows 10
2. **Browser version:** Samsung A11 (Android 11) - Genymotion Custom Phone (Android 8)

**Comment by waguilar** [comment]
I have the same issue! >=(

**Comment by frederikprijck** [comment]
This should be solved through https://github.com/auth0/auth0-oidc-client-net/pull/243.
Even though we are still looking in improving it, it should solve the issue mentioned here.
