### ISSUE TITLE
Passwordless authentication does not work.

### ISSUE THREAD

**Issue by oguduvictor** [auth0-samples/auth0-xamarin-oidc-samples#7]
I have been trying to use the passwordless authentication, but the library doesn't support passwordless authentication.

**Comment by jerriep** [comment]
@oguduvictor 

You will need to change the template for your hosted login page. In the Dashboard go to the Hosted Pages menu, and for the _Login_ page select the option **Lock (Passwordless)**. Rememeber to save the changes.

This will change the hosted login page to use Passwordless instead.

<img width="1196" alt="hosted_pages" src="https://user-images.githubusercontent.com/1006420/29125443-524aa170-7ce1-11e7-8f39-6b02a838deef.png">
