### ISSUE TITLE
How to logout

### ISSUE THREAD

**Issue by jsonkile** [auth0-samples/auth0-xamarin-oidc-samples#8]
Please i am new to this, i would like to know how to log users out on both platforms, thanks

**Comment by jerriep** [comment]
Please view the Xamarin Quickstart which explains how to do this:
https://auth0.com/docs/quickstart/native/xamarin

**Comment by gitizenme** [comment]
I'm not finding anything in the quick start regarding how to **logout** a user. Am I missing something or is there another doc that has the details?

**Comment by jerriep** [comment]
@gitizenme Hmm, I am not sure whether that was removed... Basically, your application manages the state which stores the fact that the user is logged in, right? So all you need to do is to clear that state in your application. How exactly that happens is dependent on you.

**Comment by gitizenme** [comment]
@jerriep Okay, that's what we currently have implemented in the app. Just wanted to double check as to the best practice.

**Comment by luminousAvocado** [comment]
@gitizenme I'm able to remove the credentials from our app and log them out of our application session, but
how can we use the endpoint "https://sample.auth0.com/v2/logout" to log them out of their Auth0 session, in xamarin.forms?
