### ISSUE TITLE
iOS Xamarin: The snippet code on the sample is not matching the documentation

### ISSUE THREAD

**Issue by benlizar** [auth0-samples/auth0-xamarin-oidc-samples#9]
Actual result
On the snippet code, there is a mismatch comparing to the Documentation.
<img width="822" alt="domain name _ snippet" src="https://user-images.githubusercontent.com/36707032/36493753-b7efcda6-1706-11e8-92e4-a75d347897ab.png">
<img width="837" alt="domain name_ code" src="https://user-images.githubusercontent.com/36707032/36493754-b80eb7e8-1706-11e8-9ea7-4568227ada11.png">

**Comment by jerriep** [comment]
Auth0 is populating those values. I am using the correct variables. If this is an issue it should be opened on auth0/auth0-docs repo

**Comment by albertoperdomo** [comment]
Looks like the variables are correctly injected, on iOS into the source code, on Android into a resource file (Strings.xml).
